db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "1525"
  dbname: "tdb123"

redis:
  host: "localhost:6379"
  password: ""
  db: 0
  channel_pub_event: channel_pub_event
server:
  host: "localhost"
  port: "8080"
